apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  namespace: authentication
  labels:
    app: authentication
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
      - name: authentication
        image: authentication:20250604-2222
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
        env:
        - name: DB_USER
          value: "fidelity"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: DB_HOST
          value: postgres.database.svc.cluster.local
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "authentication_db"
        - name: AUTH_PORT
          value: "8083"
        - name: CLIENT_PORT
          value: "8082"
        - name: JWT_SECRET
          value: ""
        - name: GOOGLE_CLIENT_ID
          value: ""
        - name: GOOGLE_CLIENT_SECRET
          value: ""
