apiVersion: v1
kind: Service
metadata:
  name: authentication
  namespace: authentication
spec:
  type: NodePort
  selector:
    app: authentication
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30081
